# Generated by Django 6.0.7 on 2026-09-06 17:08

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    # Keep legacy gallery IDs as scalar state until migration 0008 removes them.
    # This lets existing databases upgrade without the former gallery app.
    operations = [
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EXC', 'Club Executive'), ('ADM', 'Club Administrator')], default='EXC', max_length=20)),
                ('bypass_confirmation_restrictions', models.BooleanField(default=False, help_text='This allows execs to publish changes without approval by the club administrator')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club Executive Membership',
                'verbose_name_plural': 'Club Executive Memberships',
            },
        ),
        migrations.CreateModel(
            name='ClubWhyJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Insert a title for your reason to join the club.', max_length=30)),
                ('description', models.TextField(help_text='Insert a detailed description for your reason to join the club.', max_length=300)),
                ('index', models.IntegerField(help_text='The order in which this reason will be displayed.')),
            ],
            options={
                'verbose_name': 'Why Join',
                'verbose_name_plural': 'Why Join',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='GalleryExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Extra Fields',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insert the Name of your club', max_length=100)),
                ('preview_description', models.TextField(help_text='Insert a small description for your club. The long description is filled below.', max_length=200, null=True)),
                ('description', models.TextField(help_text='Insert a long description for your club. This is where you can describe your club in detail.', max_length=500, null=True)),
                ('repetition', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('NOTIFIED', 'Notified')], help_text="How often does your club meet? If your club meets on a different schedule, please select 'Weekly' and specify in the description.", max_length=10, null=True)),
                ('classroom_code', models.CharField(help_text="This does not need an input if there is no google classroom code. *It will not be visable when selected 'Not Accepting' in the field below.", max_length=10, null=True)),
                ('accepting_applicants', models.CharField(choices=[('AC', 'Accepting'), ('WA', 'Not Accepting'), ('OE', 'Open To Everyone')], help_text="Select 'Accepting' if applications are required. Select 'Open To Everyone' for google classroom code", max_length=16, null=True)),
                ('application_form_link', models.URLField(blank=True, help_text="This can be either a google classroom invite link or a application form link *It will not be visable when selected 'Not Accepting' in the field below.", max_length=250, null=True)),
                ('announcement', models.CharField(help_text='This is where you announce application news.', null=True)),
                ('day_of_meeting', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=10, null=True)),
                ('time', models.TimeField(null=True)),
                ('room_number', models.PositiveIntegerField(null=True)),
                ('teacher_advisor', models.CharField(help_text='Please insert the name of the teacher. Please insert Mr./Mrs./Ms. , followed by the last name', max_length=20)),
                ('tagline', models.CharField(blank=True, help_text="The tagline is the title about your club. Make it intruiging such as 'A community of curious minds'", max_length=30, null=True)),
                ('join_instructions', models.TextField(default='Use the google classroom code or application form link to join.', help_text="This is where you tell the students how to join, such as using a google classroom code or a link to a form. *It will not be visible when selected 'Not Accepting' in the field below.", max_length=500)),
                ('category', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('gallery', models.BigIntegerField(blank=True, null=True, db_column='gallery_id')),
            ],
        ),
        migrations.CreateModel(
            name='ClubAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('pinned', models.BooleanField(default=False, help_text='Whether or not the post should be pinned to the top of the page.')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_announcement', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Announcement',
                'verbose_name_plural': 'Club Announcement',
            },
        ),
        migrations.CreateModel(
            name='ClubChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(help_text='Changed Value')),
                ('status', models.CharField(choices=[('PND', 'Pending Approval'), ('APR', 'Approved'), ('RJC', 'Rejected')], default='PND', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, max_length=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_edits', to='clubs.club')),
            ],
        ),
    ]
