# Generated by Django 6.0.4 on 2026-04-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
