# Generated by Django 6.0.4 on 2026-05-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clubs', '0002_alter_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='auth.group'),
        ),
    ]
