# Generated by Django 6.0.7 on 2026-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='announcement',
            field=models.CharField(blank=True, help_text='This is where you announce application news.', null=True),
        ),
    ]
