# Generated by Django 6.0.4 on 2026-05-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='group',
        ),
    ]
