# Generated by Django 6.0.7 on 2026-09-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='announcement',
        ),
        migrations.AlterField(
            model_name='clubannouncement',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clubannouncement',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
