# Generated by Django 6.0.5 on 2026-06-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_socialmedia_clubs_socia_content_cc271f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='applicationForm',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='tagline',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
