# Generated by Django 6.0.6 on 2026-06-22 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_socialmedia_clubs_socia_content_cc271f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_join_reasons', to='clubs.club')),
            ],
        ),
    ]
