# Generated by Django 6.0.4 on 2026-05-03 23:50

import clubs.models
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_club_group'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='clubs/images'),
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='ClubGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to=clubs.models.get_upload_path)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='', max_length=500)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleryImage', to='clubs.club')),
            ],
        ),
    ]
