# Generated by Django 6.0.6 on 2026-06-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_whyjoin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whyjoin',
            options={'verbose_name': 'Why Join', 'verbose_name_plural': 'Why Join'},
        ),
    ]
