# Generated by Django 6.0.7 on 2026-09-07 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_club_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubannouncement',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This does not reflect the post status of the announcement, it only reads the current date/time.'),
        ),
    ]
