# Generated by Django 6.0.5 on 2026-05-22 12:32

import clubs.models
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_image_club_tags_clubgalleryimage'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='tags',
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=taggit.managers.TaggableManager(blank=True, help_text='Select categories for this club', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='club',
            name='classroom_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='day_of_meeting',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='room_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='teacher_advisor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubgalleryimage',
            name='category',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default='clubs/default.png', upload_to=clubs.models.get_upload_path_club),
        ),
        migrations.AlterField(
            model_name='clubgalleryimage',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='clubgalleryimage',
            name='image',
            field=models.ImageField(upload_to=clubs.models.get_upload_path_club_gallery),
        ),
        migrations.CreateModel(
            name='ClubSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('IG', 'Instagram'), ('GH', 'GitHub'), ('YT', 'YouTube'), ('TT', 'TikTok'), ('DC', 'Discord'), ('TR', 'Threads'), ('FB', 'Facebook'), ('X', 'Twitter/X'), ('LI', 'LinkedIn'), ('WS', 'Website'), ('OT', 'Other')], default='OT', max_length=2)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialMedia', to='clubs.club')),
            ],
        ),
    ]
