# Generated by Django 6.0.5 on 2026-06-07 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_applicationform_club_tagline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='applicationForm',
            new_name='applicationFormLink',
        ),
    ]
