# Generated by Django 6.0.7 on 2026-09-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_clubannouncement_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubannouncement',
            name='pinned',
        ),
        migrations.AddField(
            model_name='clubannouncement',
            name='expiry',
            field=models.DateTimeField(help_text='When does this post expire? When expired, it will be marked as resolved in the announcment section.', null=True),
        ),
        migrations.AddField(
            model_name='clubannouncement',
            name='popup',
            field=models.BooleanField(default=False, help_text='Determines whether popup is enabled for this announcement. Regardless, it will be shown in the announcements section.'),
        ),
    ]
