# Generated by Django 6.0.5 on 2026-06-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_rename_applicationform_club_applicationformlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='announcement',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='applicationFormLink',
            field=models.URLField(blank=True),
        ),
    ]
