# Generated by Django 6.0.5 on 2026-06-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_announcement_alter_club_applicationformlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='acceptingApplicants',
            field=models.CharField(blank=True, choices=[('ACCEPTING', 'Accepting'), ('NOT ACCEPTING', 'Not Accepting'), ('OPEN TO EVERYONE', 'Open To Everyone')], max_length=16),
        ),
    ]
