# Generated by Django 6.0.4 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_remove_legacy_gallery")
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(
                help_text="Insert the Name of your club", max_length=100, unique=True
            )
        )
    ]
