# Generated by Django 6.0.7 on 2026-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_club_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='room_number',
        ),
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, help_text='A room number or general name of the location.', null=True),
        ),
    ]
