# Generated by Django 6.0.5 on 2026-06-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_club_acceptingapplicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='acceptingApplicants',
            field=models.CharField(blank=True, choices=[('ACCEPTING', 'Accepting'), ('NOT ACCEPTING', 'Not Accepting'), ('OPEN TO EVERYONE', 'Open To Everyone')], help_text="Select 'Accepting' if applications are required. Select 'Open To Everyone' for google classroom code", max_length=16),
        ),
    ]
