# Generated by Django 6.0.5 on 2026-06-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_club_acceptingapplicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='applicationFormLink',
            field=models.URLField(blank=True, help_text='This can be either a google classroom invite linkor a application form link'),
        ),
    ]
