# Generated by Django 6.0.7 on 2026-09-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_remove_club_room_number_club_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='visable',
            field=models.BooleanField(default=True, help_text='Is it visable to the public?'),
        ),
    ]
