# Generated by Django 6.0.7 on 2026-09-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_club_visable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='visable',
        ),
        migrations.AddField(
            model_name='club',
            name='visible',
            field=models.BooleanField(default=True, help_text='Is it visible to the public?'),
        ),
        migrations.AlterField(
            model_name='club',
            name='application_form_link',
            field=models.URLField(blank=True, help_text="This can be either a google classroom invite link or a application form link *It will not be visible when selected 'Not Accepting' in the field below.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='classroom_code',
            field=models.CharField(help_text="This does not need an input if there is no google classroom code. *It will not be visible when selected 'Not Accepting' in the field below.", max_length=10, null=True),
        ),
    ]
