# Generated by Django 6.0.5 on 2026-06-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_alter_club_applicationformlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='applicationFormLink',
            field=models.URLField(blank=True, help_text='This can be either a google classroom invite link or a application form link'),
        ),
    ]
