# Generated by Django 6.0.5 on 2026-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_alter_club_applicationformlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='classroom_code',
            field=models.CharField(blank=True, help_text="This does not need an input if there is no google classroom code. *It will not be visable when selected 'Not Accepting' in the field below.", max_length=10, null=True),
        ),
    ]
