# Generated by Django 6.0.7 on 2026-09-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_remove_club_membership_and_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='classroom_code',
            field=models.CharField(blank=True, help_text="This does not need an input if there is no google classroom code. *It will not be visible when selected 'Not Accepting' in the field below.", max_length=10, null=True),
        ),
    ]
