# Generated by Django 6.0.5 on 2026-06-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_alter_club_classroom_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='acceptingApplicants',
            new_name='accepting_applicants',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='applicationFormLink',
            new_name='application_form_link',
        ),
    ]
