# Generated by Django 6.0.7 on 2026-09-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_alter_club_classroom_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubwhyjoin',
            options={'ordering': ['index', 'id'], 'verbose_name': 'Why Join', 'verbose_name_plural': 'Why Join'},
        ),
    ]
