# Generated by Django 6.0.5 on 2026-06-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_rename_acceptingapplicants_club_accepting_applicants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='teacher_advisor',
            field=models.CharField(blank=True, help_text='Please insert the name of the teacher. Please insert Mr./Mrs./Ms. , followed by the last name', max_length=20),
        ),
    ]
