# Generated by Django 6.0.7 on 2026-09-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_alter_clubwhyjoin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubwhyjoin',
            name='index',
            field=models.PositiveIntegerField(help_text='The order in which this reason will be displayed.'),
        ),
    ]
