# Generated by Django 6.0.5 on 2026-06-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_alter_club_teacher_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='announcement',
            field=models.CharField(help_text='This is where you announce application news.', null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Insert the Name of your club', max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='preview_description',
            field=models.CharField(blank=True, help_text='Insert a small description for your club. The long description is filled below.', max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='tagline',
            field=models.CharField(blank=True, help_text="The tagline is the title about your club. Make it intruiging such as 'A community of curious minds", max_length=30),
        ),
    ]
