# Generated by Django 6.0.7 on 2026-09-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_alter_clubwhyjoin_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubWhyJoin',
        ),
    ]
