# Generated by Django 6.0.7 on 2026-09-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_delete_clubwhyjoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='repetition',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Biweekly'), ('MONTHLY', 'Monthly'), ('NOTIFIED', 'Notified')], help_text="How often does your club meet? If your club meets on a different schedule, please select 'Notified'.", max_length=10, null=True),
        ),
    ]
