# Generated by Django 6.0.6 on 2026-06-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_alter_club_application_form_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='accepting_applicants',
            field=models.CharField(blank=True, choices=[('ACPT', 'Accepting'), ('NACPT', 'Not Accepting'), ('OpnToEvryne', 'Open To Everyone')], help_text="Select 'Accepting' if applications are required. Select 'Open To Everyone' for google classroom code", max_length=16),
        ),
        migrations.AlterField(
            model_name='club',
            name='tagline',
            field=models.CharField(blank=True, help_text="The tagline is the title about your club. Make it intruiging such as 'A community of curious minds'", max_length=30),
        ),
    ]
