# Generated by Django 6.0.7 on 2026-10-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_alter_club_repetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='accepting_applicants',
            field=models.CharField(choices=[('AC', 'Accepting'), ('WA', 'Not Accepting'), ('OE', 'Open To Everyone')], help_text="Select 'Accepting' if applications are required. Select 'Open To Everyone' for google classroom code (Max char: 16)", max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='application_form_link',
            field=models.URLField(blank=True, help_text="This can be either a google classroom invite link or a application form link *It will not be visible when selected 'Not Accepting' in the field below. (Max char: 250)", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='classroom_code',
            field=models.CharField(blank=True, help_text="This does not need an input if there is no google classroom code. *It will not be visible when selected 'Not Accepting' in the field below. (Max char: 10)", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(help_text='Insert a long description for your club. This is where you can describe your club in detail. (Max char: 500)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='join_instructions',
            field=models.TextField(default='Use the google classroom code or application form link to join.', help_text="This is where you tell the students how to join, such as using a google classroom code or a link to a form. *It will not be visible when selected 'Not Accepting' in the field below. (Max char: 500)", max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Insert the Name of your club. (Max Char: 100)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='preview_description',
            field=models.TextField(help_text='Insert a small description for your club. The long description is filled below. (Max char: 200)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='tagline',
            field=models.CharField(help_text="The tagline is the title about your club. Make it intruiging such as 'A community of curious minds' (Max char: 30)", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='teacher_advisor',
            field=models.CharField(help_text='Please insert the name of the teacher. Please insert Mr./Mrs./Ms. , followed by the last nameMultiple teachers are allowed. (Max char: 40)', max_length=40),
        ),
    ]
