# Generated by Django 6.0.6 on 2026-06-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_alter_club_accepting_applicants_alter_club_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='room_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
