# Generated by Django 6.0.7 on 2026-10-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_alter_club_accepting_applicants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='accepting_applicants',
            field=models.CharField(choices=[('AC', 'Accepting'), ('NA', 'Not Accepting'), ('OE', 'Open To Everyone')], help_text="Select 'Accepting' if applications are required. Select 'Open To Everyone' for google classroom code (Max char: 16)", max_length=16, null=True),
        ),
    ]
