# Generated by Django 6.0.6 on 2026-06-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_alter_club_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='accepting_applicants',
            field=models.CharField(blank=True, choices=[('AC', 'Accepting'), ('WA', 'Not Accepting'), ('OE', 'Open To Everyone')], help_text="Select 'Accepting' if applications are required. Select 'Open To Everyone' for google classroom code", max_length=16),
        ),
    ]
