# Generated by Django 6.0.6 on 2026-06-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_whyjoin_options'),
        ('clubs', '0019_alter_club_room_num'),
    ]

    operations = [
    ]
