# Generated by Django 6.0.7 on 2026-10-08 15:33

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_alter_club_accepting_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=markdownx.models.MarkdownxField(help_text='Insert a long description for your club. This is where you can describe your club in detail. (Max char: 500)', max_length=500, null=True),
        ),
    ]
