# Generated by Django 6.0.6 on 2026-06-25 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_merge_20260625_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='accepting_applicants',
            field=models.CharField(blank=True, choices=[('AC', 'Accepting'), ('WA', 'Not Accepting'), ('OE', 'Open To Everyone')], help_text="Select 'Accepting' if applications are required. Select 'Open To Everyone' for google classroom code", max_length=16),
        ),
        migrations.CreateModel(
            name='ClubAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('pinned', models.BooleanField(default=False, help_text='Whether or not the post should be pinned to the top of the page.')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_announcement', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Announcement',
                'verbose_name_plural': 'Club Announcement',
            },
        ),
        migrations.CreateModel(
            name='ClubWhyJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('index', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_join_reasons', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Why Join',
                'verbose_name_plural': 'Why Join',
                'ordering': ['index'],
            },
        ),
        migrations.DeleteModel(
            name='WhyJoin',
        ),
    ]
