# Generated by Django 6.0.6 on 2026-07-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_alter_club_accepting_applicants'),
        ('clubs', '0021_alter_club_accepting_applicants_clubannouncement_and_more'),
    ]

    operations = [
    ]
