# Generated by Django 6.0.7 on 2026-10-08 15:44

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_alter_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubannouncement',
            name='description',
            field=markdownx.models.MarkdownxField(max_length=500, null=True),
        ),
    ]
