# Generated by Django 6.0.7 on 2026-07-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0022_merge_20260705_0050"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="room_num",
            new_name="room_number",
        ),
    ]
