# Generated by Django 6.0.7 on 2026-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0023_rename_room_num_club_room_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Insert a long description for your club. This is where you can describe your club in detail.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="preview_description",
            field=models.TextField(
                blank=True,
                help_text="Insert a small description for your club. The long description is filled below.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="repetition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEEKLY", "Weekly"),
                    ("BIWEEKLY", "Biweekly"),
                    ("MONTHLY", "Monthly"),
                ],
                help_text="How often does your club meet? If your club meets on a different schedule, please select 'Weekly' and specify in the description.",
                max_length=10,
            ),
        ),
    ]
