# Generated by Django 6.0.7 on 2026-07-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0024_alter_club_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="repetition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEEKLY", "Weekly"),
                    ("BIWEEKLY", "Biweekly"),
                    ("MONTHLY", "Monthly"),
                    ("NOTIFIED", "Notified"),
                ],
                help_text="How often does your club meet? If your club meets on a different schedule, please select 'Weekly' and specify in the description.",
                max_length=10,
            ),
        ),
    ]
