# Generated by Django 6.0.7 on 2026-07-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0025_alter_club_repetition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubwhyjoin",
            name="description",
            field=models.TextField(
                help_text="Insert a detailed description for your reason to join the club.",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="clubwhyjoin",
            name="index",
            field=models.IntegerField(
                help_text="The order in which this reason will be displayed."
            ),
        ),
        migrations.AlterField(
            model_name="clubwhyjoin",
            name="title",
            field=models.CharField(
                help_text="Insert a title for your reason to join the club.",
                max_length=200,
            ),
        ),
    ]
