# Generated by Django 6.0.7 on 2026-07-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_alter_clubwhyjoin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='application_form_link',
            field=models.URLField(blank=True, help_text="This can be either a google classroom invite link or a application form link *It will not be visable when selected 'Not Accepting' in the field below.", max_length=250),
        ),
    ]
