# Generated by Django 5.2.16 on 2026-08-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_alter_club_id_alter_clubannouncement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='join_instructions',
            field=models.TextField(blank=True, help_text="This is where you tell the students how to join, such as using a google classroom code or a link to a form. *It will not be visable when selected 'Not Accepting' in the field below.", max_length=500),
        ),
    ]
