# Generated by Django 6.0.7 on 2026-08-11 16:10

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_alter_club_join_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(default='defaults/clubs/default.png', upload_to=clubs.models.get_upload_path_club),
        ),
    ]
