# Generated by Django 6.0.7 on 2026-08-13 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_alter_club_image'),
        ('photologue', '0014_alter_watermark_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='gallery',
            field=models.OneToOneField(blank=True, help_text='The photo gallery for this club.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='photologue.gallery'),
        ),
        migrations.DeleteModel(
            name='ClubGalleryImage',
        ),
    ]
