# Generated by Django 6.0.7 on 2026-08-13 04:33

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_club_gallery_delete_clubgalleryimage'),
        ('photologue', '0014_alter_watermark_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='photologue.gallery'),
        ),
        migrations.CreateModel(
            name='GalleryExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.OneToOneField(blank=True, help_text='The photo gallery for this club.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club', to='photologue.gallery')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Extra Fields',
            },
        ),
    ]
