# Generated by Django 6.0.7 on 2026-08-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0034_alter_club_gallery_galleryextended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
