# Generated by Django 6.0.7 on 2026-08-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_rename_image_club_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='thumbnail',
        ),
    ]
