# Generated by Django 6.0.7 on 2026-08-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_clubchanges_clubmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubchanges',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending Approval'), ('APR', 'Approved'), ('RJC', 'Rejected')], default='PND', max_length=10),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='role',
            field=models.CharField(choices=[('EXC', 'Club Executive'), ('ADM', 'Club Administrator')], default='EXC', max_length=20),
        ),
    ]
