# Generated by Django 6.0.7 on 2026-08-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0039_alter_club_accepting_applicants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='join_instructions',
            field=models.TextField(default='Use the google classroom code or application form link to join.', help_text="This is where you tell the students how to join, such as using a google classroom code or a link to a form. *It will not be visable when selected 'Not Accepting' in the field below.", max_length=500),
        ),
    ]
