# Generated by Django 6.0.7 on 2026-08-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_alter_club_join_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubwhyjoin',
            name='description',
            field=models.TextField(help_text='Insert a detailed description for your reason to join the club.', max_length=300),
        ),
        migrations.AlterField(
            model_name='clubwhyjoin',
            name='title',
            field=models.CharField(help_text='Insert a title for your reason to join the club.', max_length=30),
        ),
    ]
