# Generated by Django 6.0.7 on 2026-09-07 05:13

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This is the subtitle of the page. It is the BOTTOM of the title section (secondary color). *NOT REQUIRED', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='tagline',
            field=models.TextField(blank=True, help_text='This is the bullet points of the title. It should be short and tells the user a bit about the page. *NOT REQUIRED', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='school_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='school_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='The phone number should include the area code (+1), followed by the digits with no spaces or a non-numerial character.', max_length=128, null=True, region=None),
        ),
    ]
