# Generated by Django 6.0.6 on 2026-07-05 04:39

import osm_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='school_mascot',
            field=models.CharField(blank=True, help_text="This is the school's mascot. (e.g, Wildcat, Rattler) *Non-plural*.", max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=osm_field.fields.OSMField(blank=True, help_text="Drag the pin to the location of your club's meeting place. You can also search for a location in the search bar.", lat_field='location_lat', lon_field='location_lon', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(default='management/default.png', help_text='This is the icon that appears in the browser tab. It should be a square image, preferably 32x32 pixels.', upload_to='management/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stuco_image',
            field=models.ImageField(default='management/default.png', help_text="This is the image for the club's logo. It should be a square image, preferably 300x300 pixels.", upload_to='management/'),
        ),
    ]
