# Generated by Django 6.0.6 on 2026-06-28 17:12

import osm_field.fields
import osm_field.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=osm_field.fields.OSMField(blank=True, lat_field='location_lat', lon_field='location_lon'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_lat',
            field=osm_field.fields.LatitudeField(blank=True, null=True, validators=[osm_field.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_lon',
            field=osm_field.fields.LongitudeField(blank=True, null=True, validators=[osm_field.validators.validate_longitude]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='SCHOOL STUCO', help_text='The name of the School Council', max_length=50),
        ),
    ]
