# Generated by Django 6.0.6 on 2026-07-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_location_location_alter_location_location_lat_and_more'),
        ('management', '0002_sitesettings_school_mascot_alter_location_location_and_more'),
    ]

    operations = [
    ]
