# Generated by Django 6.0.7 on 2026-09-07 14:23

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_sitesettings_site_logo_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='This is the icon that represents your school. This image will be displayed on the navigation bar and the homepage.', upload_to=management.models.SiteLogoRename),
        ),
    ]
