# Generated by Django 6.0.6 on 2026-07-05 04:50

import osm_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_merge_20260705_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=osm_field.fields.OSMField(blank=True, help_text="Drag the pin to the location of your club's meeting place. You can also search for a location in the search bar.", lat_field='location_lat', lon_field='location_lon', null=True),
        ),
    ]
