# Generated by Django 6.0.7 on 2026-09-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_sitesettings_site_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='council_name',
        ),
    ]
