# Generated by Django 6.0.7 on 2026-07-09 20:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_location_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="school_primary_color",
            field=colorfield.fields.ColorField(
                default="#000000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
