# Generated by Django 6.0.7 on 2026-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_sitesettings_council_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='maintainance_mode',
            field=models.BooleanField(default=True, help_text='Disable when site is ready for publishing.'),
        ),
    ]
