# Generated by Django 6.0.7 on 2026-07-09 20:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_sitesettings_school_primary_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="school_secondary_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="This is the secondary color of the school. It should be a hex code (e.g., #000000).",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="school_tertiary_color",
            field=colorfield.fields.ColorField(
                default="#FF0000",
                help_text="This is the 'accent' color of the site. It should be a hex code (e.g., #FFFFFF).",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="school_primary_color",
            field=colorfield.fields.ColorField(
                default="#000000",
                help_text="This is the primary color of the school. It should be a hex code (e.g., #FF0000).",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
    ]
