# Generated by Django 6.0.7 on 2026-07-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_sitesettings_school_secondary_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_name",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="council_name",
            field=models.CharField(
                default="STUCO",
                help_text="The name of the council (e.g, SAC)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="school_name",
            field=models.CharField(
                default="SCHOOL",
                help_text="The name of the school (Use short form S.S)",
                max_length=40,
            ),
        ),
    ]
