# Generated by Django 6.0.7 on 2026-09-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_require_site_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='maintainance_mode',
            field=models.BooleanField(default=True, help_text='Disable when site is ready for publishing. NOTE: It will take up to 30 seconds to update.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='school_mascot',
            field=models.CharField(help_text="This is the school's mascot. (e.g, Wildcat, Rattler) *Non-plural*.", max_length=50, null=True),
        ),
    ]
