# Generated by Django 6.0.7 on 2026-07-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_remove_sitesettings_site_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="school_name",
            field=models.CharField(
                default="SCHOOL",
                help_text="The name of the school *Use short form S.S (e.g, Richmond Green S.S)",
                max_length=40,
            ),
        ),
    ]
