# Generated by Django 6.0.7 on 2026-10-03 03:12

import management.legalDefaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_sitesettings_maintainance_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_service', models.CharField(default=management.legalDefaults.TermsService, max_length=10000, verbose_name='Terms of Service')),
                ('privacy_policy', models.CharField(default=management.legalDefaults.PrivacyPolicy, max_length=10000, verbose_name='Privacy Policy')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
