# Generated by Django 6.0.7 on 2026-07-10 03:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_alter_sitesettings_school_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="school_email",
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="school_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
