# Generated by Django 6.0.7 on 2026-10-07 04:45

import management.legalDefaults
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_sitesettings_maintainance_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_service', markdownx.models.MarkdownxField(default=management.legalDefaults.termsService, max_length=10000, verbose_name='Terms of Service')),
                ('privacy_policy', markdownx.models.MarkdownxField(default=management.legalDefaults.privacyPolicy, max_length=10000, verbose_name='Privacy Policy')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Settings',
                'verbose_name_plural': 'Legal Settings',
            },
        ),
    ]
