# Generated by Django 6.0.7 on 2026-10-03 15:04

import management.legalDefaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_legal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legal',
            options={'verbose_name': 'Legal Settings', 'verbose_name_plural': 'Legal Settings'},
        ),
        migrations.AlterField(
            model_name='legal',
            name='privacy_policy',
            field=models.TextField(default=management.legalDefaults.PrivacyPolicy, max_length=10000, verbose_name='Privacy Policy'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='terms_service',
            field=models.TextField(default=management.legalDefaults.TermsService, max_length=10000, verbose_name='Terms of Service'),
        ),
    ]
