# Generated by Django 6.0.7 on 2026-07-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_sitesettings_school_email_sitesettings_school_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="frontend_url",
            field=models.URLField(
                blank=True, help_text="The external url of frontend", max_length=100
            ),
        ),
    ]
