# Generated by Django 6.0.7 on 2026-10-03 15:18

import management.legalDefaults
import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_legal_options_alter_legal_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='privacy_policy',
            field=markdownx.models.MarkdownxField(default=management.legalDefaults.PrivacyPolicy, max_length=10000, verbose_name='Privacy Policy'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='terms_service',
            field=markdownx.models.MarkdownxField(default=management.legalDefaults.TermsService, max_length=10000, verbose_name='Terms of Service'),
        ),
    ]
