# Generated by Django 6.0.7 on 2026-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_sitesettings_frontend_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="frontend_url",
            field=models.URLField(
                default="http://localhost:3000",
                help_text="The external url of frontend",
                max_length=100,
            ),
        ),
    ]
