# Generated by Django 5.2.16 on 2026-07-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_location_id_alter_sitesettings_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_site_name', models.CharField(choices=[('HM', 'Home'), ('CL', 'Clubs'), ('GL', 'Gallery'), ('AB', 'About')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('tagline', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
