# Generated by Django 5.2.16 on 2026-07-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_location_id_alter_pagesettings_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageSettings',
            new_name='PageSetting',
        ),
    ]
