# Generated by Django 6.0.5 on 2026-08-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_rename_pagesettings_pagesetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageSetting',
            new_name='PageSettings',
        ),
    ]
