# Generated by Django 6.0.5 on 2026-08-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_rename_pagesetting_pagesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagesettings',
            options={'verbose_name': 'Page Configuration'},
        ),
    ]
