# Generated by Django 5.2.16 on 2026-08-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_pagesettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This is the subtitle of the page. It is the BOTTOM of the title section (secondary color). *NOT REQUIRED', max_length=30),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='tagline',
            field=models.TextField(blank=True, help_text='This is the bullet points of the title. It should be short and tells the user a bit about the page. *NOT REQUIRED', max_length=200),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='title',
            field=models.CharField(help_text='This is the title of the page. It is the TOP of the title section.', max_length=30),
        ),
    ]
