# Generated by Django 5.2.16 on 2026-08-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_location_location_alter_pagesettings_subtitle_and_more'),
        ('management', '0018_alter_pagesettings_subtitle_and_more'),
    ]

    operations = [
    ]
