# Generated by Django 6.0.7 on 2026-08-11 01:14

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_merge_20260807_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(default='management/favicon.png', help_text='This is the icon that appears in the browser tab. It should be a square image, preferably 32x32 pixels.', upload_to=management.models.FaviconRename),
        ),
    ]
