# Generated by Django 6.0.7 on 2026-08-11 02:19

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fav_crop',
            field=image_cropping.fields.ImageRatioField('favicon', '32x32', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='fav crop'),
        ),
    ]
