# Generated by Django 6.0.7 on 2026-08-11 04:32

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_remove_sitesettings_fav_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon_cropping',
            field=image_cropping.fields.ImageRatioField('favicon', '32x32', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The small icon next to the browser tab title', hide_image_field=False, size_warning=False, verbose_name='favicon cropping'),
        ),
    ]
