# Generated by Django 6.0.7 on 2026-08-11 16:10

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_sitesettings_favicon_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(default='defaults/management/favicon.png', help_text='This is the icon that appears in the browser tab. It should be a square image, preferably 32x32 pixels.', upload_to=management.models.FaviconRename),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stuco_image',
            field=models.ImageField(default='defaults/management/default.png', help_text="This is the image for the club's logo. It should be a square image, preferably 300x300 pixels.", upload_to='upload/management/'),
        ),
    ]
