# Generated by Django 6.0.7 on 2026-08-11 16:21

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_sitesettings_favicon_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon_cropping',
            field=image_cropping.fields.ImageRatioField('favicon', '32x32', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='The small icon next to the browser tab title. Save new uploaded image then reopen this page to view your new uploaded photo.', hide_image_field=False, size_warning=False, verbose_name='favicon cropping'),
        ),
    ]
