# Generated by Django 6.0.7 on 2026-08-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_sitesettings_favicon_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='captcha',
            field=models.CharField(blank=True, choices=[('LOGIN', 'Login'), ('REGISTER', 'Register'), ('ENTERING', 'Entering')], max_length=20),
        ),
    ]
