# Generated by Django 6.0.7 on 2026-08-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_sitesettings_captcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='captcha',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
