# Generated by Django 6.0.7 on 2026-08-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_alter_sitesettings_captcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='captcha',
            field=models.CharField(blank=True, choices=[('LOGIN', 'Login'), ('REGISTER', 'Register'), ('ENTERING', 'Entering')], max_length=20, null=True),
        ),
    ]
