# Generated by Django 6.0.7 on 2026-08-14 04:39

import image_cropping.fields
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_sitesettings_captcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='stuco_image',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(default='defaults/management/default.png', help_text='This is the icon that represents your school', upload_to=management.models.SiteLogoRename),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo_cropping',
            field=image_cropping.fields.ImageRatioField('site_logo', '128x128', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Save new uploaded image then re-open this page to view your new uploaded photo.', hide_image_field=False, size_warning=False, verbose_name='site logo cropping'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(default='defaults/management/default.png', help_text='This is the icon that appears in the browser tab. It should be a square image, preferably 32x32 pixels.', upload_to=management.models.FaviconRename),
        ),
    ]
