# Generated by Django 6.0.7 on 2026-08-14 06:44

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_remove_sitesettings_stuco_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo_cropping',
            field=image_cropping.fields.ImageRatioField('site_logo', '80x80', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Save new uploaded image then re-open this page to view your new uploaded photo.', hide_image_field=False, size_warning=False, verbose_name='site logo cropping'),
        ),
    ]
