# Generated by Django 6.0.7 on 2026-08-28 14:33

import osm_field.fields
import osm_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_alter_sitesettings_site_logo_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=osm_field.fields.OSMField(help_text="Click on the map of the school's location. You can also search for it in the search bar.", lat_field='location_lat', lon_field='location_lon', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_lat',
            field=osm_field.fields.LatitudeField(null=True, validators=[osm_field.validators.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_lon',
            field=osm_field.fields.LongitudeField(null=True, validators=[osm_field.validators.validate_longitude]),
        ),
    ]
