# Generated by Django 6.0.7 on 2026-09-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_alter_location_location_alter_location_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_school',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_stuco',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='school_domain',
            field=models.CharField(help_text='This is the domain of the school. e.g yrdsb.ca, tdsb.on.ca, etc. This is used for email verification', max_length=50, null=True),
        ),
    ]
