# Generated by Django 6.0.7 on 2026-09-02

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0037_remove_sitesettings_about_school_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "This is the icon that appears in the browser tab. It should "
                    "be a square image, preferably 32x32 pixels."
                ),
                upload_to=management.models.FaviconRename,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_logo",
            field=models.ImageField(
                blank=True,
                help_text="This is the icon that represents your school",
                upload_to=management.models.SiteLogoRename,
            ),
        ),
    ]
