# Generated by Django 6.0.7 on 2026-09-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_alter_sitesettings_default_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('IG', 'Instagram'), ('YT', 'YouTube'), ('LI', 'LinkedIn'), ('OT', 'Other')], max_length=2, null=True)),
                ('title', models.CharField(help_text='This is needed only to override the default site title', max_length=20, null=True)),
                ('link', models.URLField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.RemoveIndex(
            model_name='socialmedia',
            name='management__content_bb9b43_idx',
        ),
        migrations.AddField(
            model_name='schoolsocialmedia',
            name='site_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='management.sitesettings'),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
