# Generated by Django 6.0.7 on 2026-09-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_schoolsocialmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsocialmedia',
            name='site_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_media', to='management.sitesettings'),
        ),
    ]
