# Generated by Django 6.0.7 on 2026-09-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_alter_schoolsocialmedia_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsocialmedia',
            name='title',
            field=models.CharField(blank=True, help_text='This is needed only to override the default site title', max_length=20, null=True),
        ),
    ]
