# Generated by Django 6.0.4 on 2026-04-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar'),
        ),
    ]
