# Generated by Django 6.0.4 on 2026-04-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='clubs.club'),
        ),
    ]
