# Generated by Django 6.0.4 on 2026-04-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='filename',
            field=models.TextField(default='<django.db.models.fields.CharField>.ics'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
