# Generated by Django 6.0.7 on 2026-09-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STUCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_name', models.CharField(default='STUCO', help_text='The name of the council (e.g, SAC)', max_length=10)),
                ('group_photo', models.ImageField(blank=True, null=True, upload_to='upload/stuco/')),
            ],
            options={
                'verbose_name': 'Student Council Settings',
                'verbose_name_plural': 'Student Council Settings',
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='This should be a short announcement that rotates on the ticker bar at the homepage.')),
            ],
            options={
                'verbose_name': 'Ticker Bar Items',
                'verbose_name_plural': 'Ticker Bar Items',
            },
        ),
    ]
