# Generated by Django 6.0.7 on 2026-09-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_items', models.TextField(blank=True, help_text='Every newline represents a new object.', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Announcement Objects',
                'verbose_name_plural': 'Announcement Objects',
            },
        ),
        migrations.CreateModel(
            name='SchoolAnnouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the announcement', null=True)),
                ('contents', models.TextField(help_text='The contents of the announcement', null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='STUCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_name', models.CharField(default='STUCO', help_text='The name of the council (e.g, SAC)', max_length=10)),
                ('group_photo', models.ImageField(blank=True, null=True, upload_to='upload/stuco/')),
                ('photo_caption', models.TextField(blank=True, help_text='A legend for the people present in the photo.', null=True)),
            ],
            options={
                'verbose_name': 'Student Council Settings',
                'verbose_name_plural': 'Student Council Settings',
            },
        ),
    ]
