# Generated by Django 6.0.7 on 2026-09-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_council', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuco',
            name='photo_caption',
            field=models.CharField(blank=True, help_text='Caption for Group Photo.', null=True),
        ),
    ]
