# Generated by Django 6.0.7 on 2026-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_council', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuco',
            name='stuco_logo',
            field=models.ImageField(blank=True, help_text='The logo that will appear on the homepage logo section.', null=True, upload_to=''),
        ),
    ]
