# Generated by Django 6.0.7 on 2026-09-19 04:21

import student_council.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_council', '0002_stuco_stuco_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuco',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to=student_council.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='stuco',
            name='stuco_logo',
            field=models.ImageField(blank=True, help_text='The logo that will appear on the homepage logo section.', null=True, upload_to=student_council.models.image_upload_path),
        ),
    ]
