# Generated by Django 6.0.7 on 2026-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_council', '0002_stuco_photo_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAnnouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the announcement', null=True)),
                ('contents', models.TextField(help_text='The contents of the announcement', null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
