# Generated by Django 6.0.7 on 2026-09-21 21:49

import django.db.models.deletion
import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0017_delete_clubwhyjoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name will automatically be generated based on the ZIP file name.', null=True)),
                ('zip_file', models.FileField(help_text='EVERYTHING within the ZIP file will be uploaded into the specified club. Photo files only.', upload_to=galleries.models.zip_upload_path)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('upload_status', models.CharField(max_length=5, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'ZIP Upload',
                'verbose_name_plural': 'ZIP Upload',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='If left blank, it will automatically generate a name for you.', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='More like an image caption, to describe what is going on. *OPTIONAL', max_length=100, null=True)),
                ('image', models.ImageField(upload_to=galleries.models.photo_upload_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('shown_in_gallery', models.BooleanField(default=False, help_text='Select this option if you want the photo to be shown in the gallery.')),
                ('shown_in_main_page', models.BooleanField(default=False, help_text="Select this option if you want the photo to be shown in your club's homepage")),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Photos',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
