# Generated by Django 6.0.7 on 2026-09-08 02:38

import django.db.models.deletion
import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0007_remove_clubannouncement_pinned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='More like an image caption, to describe what is going on. *OPTIONAL', max_length=100, null=True)),
                ('image', models.ImageField(upload_to=galleries.models.photo_upload_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Photos',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='This is like a video description about what the video is about. *OPTIONAL.', max_length=100, null=True)),
                ('link', models.URLField(blank=True, help_text='Not required, only needed for Youtube and Google Drive(Use embed code)', max_length=500, null=True)),
                ('video_file', models.FileField(upload_to=galleries.models.video_upload_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Videos',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
