# Generated by Django 6.0.7 on 2026-09-08 02:54

import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=galleries.models.video_upload_path),
        ),
    ]
