# Generated by Django 6.0.7 on 2026-09-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Photos', 'verbose_name_plural': 'Photos'},
        ),
    ]
