# Generated by Django 6.0.7 on 2026-09-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='shown_in_gallery',
            field=models.BooleanField(default=True, help_text='Select this option if you want the photo to be shown in the gallery.'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='shown_in_main_page',
            field=models.BooleanField(default=True, help_text="Select this option if you want the photo to be shown in your club's homepage"),
        ),
    ]
