# Generated by Django 6.0.7 on 2026-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_photos_shown_in_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='shown_in_gallery',
            field=models.BooleanField(default=True, help_text='Display this photo in the site-wide gallery.', verbose_name='Show in gallery'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='shown_in_main_page',
            field=models.BooleanField(default=True, help_text="Display this photo on the selected club's homepage.", verbose_name='Show on club homepage'),
        ),
    ]
