# Generated by Django 6.0.7 on 2026-09-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_photos_name_alter_videos_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='name',
            field=models.CharField(blank=True, help_text='If left blank, it will automatically generate a name for you.', max_length=50, null=True),
        ),
    ]
