# Generated by Django 6.0.7 on 2026-09-08 18:13

import django.db.models.deletion
import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_clubannouncement_pinned_and_more'),
        ('galleries', '0003_alter_photos_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(help_text='EVERYTHING within the ZIP file will be uploaded into the specified club. Videos or Photo files only.', upload_to=galleries.models.zip_upload_path)),
                ('file_type', models.CharField(choices=[('PH', 'Photos'), ('VI', 'Videos')], max_length=2)),
                ('upload_status', models.CharField(max_length=5, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'ZIP Upload',
                'verbose_name_plural': 'ZIP Upload',
            },
        ),
    ]
