# Generated by Django 6.0.7 on 2026-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_massimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(blank=True, help_text='If left blank, it will automatically generate a name for you.', max_length=50, null=True),
        ),
    ]
