# Generated by Django 6.0.7 on 2026-10-02 16:30

import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_alter_photos_shown_in_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massimport',
            name='deletion_date',
            field=models.DateField(default=galleries.models.deletion_date, editable=False, verbose_name='Automatic Deletion Date'),
        ),
    ]
