# Generated by Django 6.0.7 on 2026-09-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_massimport_name_massimport_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='shown_in_gallery',
            field=models.BooleanField(default=False, help_text='Select this option if you want the photo to be shown in the gallery.'),
        ),
        migrations.AddField(
            model_name='photos',
            name='shown_in_main_page',
            field=models.BooleanField(default=False, help_text="Select this option if you want the photo to be shown in your club's homepage"),
        ),
        migrations.AddField(
            model_name='videos',
            name='shown_in_gallery',
            field=models.BooleanField(default=False, help_text='Select this option if you want the photo to be shown in the gallery.'),
        ),
        migrations.AddField(
            model_name='videos',
            name='shown_in_main_page',
            field=models.BooleanField(default=False, help_text="Select this option if you want the photo to be shown in your club's homepage"),
        ),
        migrations.AlterField(
            model_name='massimport',
            name='name',
            field=models.CharField(blank=True, help_text='The name will automatically be generated based on the ZIP file name.', null=True),
        ),
    ]
