# Generated by Django 6.0.7 on 2026-09-21 18:32

import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_photos_shown_in_gallery_photos_shown_in_main_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massimport',
            name='file_type',
            field=models.CharField(choices=[('PH', 'Photos')], max_length=2),
        ),
        migrations.AlterField(
            model_name='massimport',
            name='zip_file',
            field=models.FileField(help_text='EVERYTHING within the ZIP file will be uploaded into the specified club. Photo files only.', upload_to=galleries.models.zip_upload_path),
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
