# Generated by Django 5.2.16 on 2026-08-05 14:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoincode',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userjoincode',
            name='max_uses',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userjoincode',
            name='uses',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userjoincode',
            name='code',
            field=models.CharField(default=users.models.get_random_code, unique=True),
        ),
        migrations.AlterField(
            model_name='userjoincode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userjoincode',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userjoincode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
