# Generated by Django 6.0.7 on 2026-09-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoincode',
            name='description',
            field=models.TextField(blank=True, help_text="A description of this qr code, e.g. 'For use in the cafeteria only.' (*NOT REQUIRED)", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userjoincode',
            name='label',
            field=models.CharField(help_text="A easily identifiable name for this qr code, e.g. 'Cafeteria'", max_length=50, null=True, verbose_name='Title'),
        ),
    ]
