# Generated by Django 5.2.16 on 2026-08-05 15:04

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userjoincode_enabled_userjoincode_max_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoincode',
            name='code',
            field=models.CharField(default=users.models.get_random_code, unique=True, verbose_name='Security Code'),
        ),
        migrations.AlterField(
            model_name='userjoincode',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userjoincode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userjoincode',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title'),
        ),
    ]
