# Generated by Django 5.2.16 on 2026-08-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userjoincode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoincode',
            name='label',
            field=models.CharField(blank=True, help_text="A easily identifiable name for this qr code, e.g. 'Cafeteria'", max_length=50, verbose_name='Title'),
        ),
    ]
