# Generated by Django 5.2.16 on 2026-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userjoincode_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userjoincode',
            options={'verbose_name': 'School User Registration QR Code'},
        ),
        migrations.AlterField(
            model_name='userjoincode',
            name='description',
            field=models.TextField(blank=True, help_text="A description of this qr code, e.g. 'For use in the cafeteria only.' (*NOT REQUIRED)", max_length=300),
        ),
    ]
