# Generated by Django 6.0.7 on 2026-08-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userjoincode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userjoincode',
            options={'verbose_name': 'Student Registration QR Code'},
        ),
    ]
