# Generated by Django 6.0.7 on 2026-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, help_text='The role applied for student council.', max_length=50, null=True),
        ),
    ]
