# Generated by Django 6.0.7 on 2026-09-02 01:18

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoincode',
            name='code',
            field=models.CharField(default=users.models.get_random_code, help_text='Unencrypted registration code -- DO NOT SHARE', unique=True, verbose_name='Security Code'),
        ),
    ]
